### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by zzwd** [RyanGlScott/BluetoothTest#2]
hi, i add main function in bluez_server.c  like this
 int main(int argc, char **argv)
 {
         init_server();
         return 0;
 }

and use gcc compile,but run find the error,can you help me?

pi@raspberrypi:~/zzw/BluezServer $ gcc -o bluez_server bluez_server.c -lbluetooth
bluez_server.c: In function ‘read_server’:
bluez_server.c:172:3: warning: function returns address of local variable [-Wreturn-local-addr]
   return input;
   ^
pi@raspberrypi:~/zzw/BluezServer $ 
pi@raspberrypi:~/zzw/BluezServer $ ./bluez_server
Registering UUID 00001101-0000-1000-8000-00805f9b34fb
Segmentation fault
pi@raspberrypi:~/zzw/BluezServer $ gdb ./bluez_server
GNU gdb (Raspbian 7.7.1+dfsg-5+rpi1) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./bluez_server...(no debugging symbols found)...done.
(gdb) r
Starting program: /home/pi/zzw/BluezServer/bluez_server 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Registering UUID 00001101-0000-1000-8000-00805f9b34fb

Program received signal SIGSEGV, Segmentation fault.
0x76f96a0c in sdp_device_record_register_binary ()
   from /usr/lib/arm-linux-gnueabihf/libbluetooth.so.3
(gdb)

**Comment by blvckcrxw** [comment]
I`m facing same problem. @zzwd how did you solve this issue?
